# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.define "box1-u20" do |web1|
    web1.vm.box = "ubuntu/focal64"
    web1.vm.hostname = "box1-u20"
    web1.vm.network "private_network", ip: "192.168.33.61"
  end  

  config.vm.define "web2" do |web2|
    web2.vm.box = "centos/7"
    web2.vm.hostname = "web2"
    web2.vm.network "private_network", ip: "192.168.33.62"
  end

  config.vm.define "box3-u18" do |web3|
    web3.vm.box = "ubuntu/bionic64"
    web3.vm.hostname = "box3-u18"
    web3.vm.network "private_network", ip: "192.168.33.63"
    #web.vm.network "forwarded_port", guest: 80, host:8080
    # web3.vm.provision "file", source: "../../authorized_keys", destination: ".ssh/authorized_keys"
  end  

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  # config.vm.provision "file", source: "../../authorized_keys", destination: ".ssh/authorized_keys"

end
